### ISSUE TITLE
Make Kanbanion run on the Desktop

### ISSUE THREAD

**Issue by Mr-Personality** [nmaggioni/Kanbanion#14]
This is extremely ambitious and I don't expect it to be possible, but it would be great if Kanbanion ran on the Windows Desktop (running automatically when Windows boots). This is where I normally keep all my reminders and current activity.

**Comment by nmaggioni** [comment]
I'm not familiar with the latest Windows releases, if you mean the lockscreen then it surely won't be doable since this is not a native application.

**Comment by Mr-Personality** [comment]
I use Windows 7. I don't even know what a lockscreen is!

**Comment by nmaggioni** [comment]
Do you mean a widget then? Unfortunately the problem stays the same, this type of application cannot be embedded that deeply in the Windows ecosystem.
