### ISSUE TITLE
Can't get it to installs

### ISSUE THREAD

**Issue by manattweb** [nmaggioni/Kanbanion#2]
Got an error when running "npm run build" from the cloned repository. Debug log attached.

[npm-debug.log.zip](https://github.com/nmaggioni/Kanbanion/files/486280/npm-debug.log.zip)

**Comment by nmaggioni** [comment]
From the log it seems that you tried to `npm install` Kanbanion directly - it is not published in the registry.

Did you clone the repo, ran `npm install`, `bower install` and `npm run build`?
I've updated the packaging command to do so automatically from now on (3a4be34).

**Comment by manattweb** [comment]
I got the app to start; however, it looks like the attachment.
![k_screenshot](https://cloud.githubusercontent.com/assets/3402707/18762193/675a5e90-80cd-11e6-95c0-36cb68b98906.png)

**Comment by manattweb** [comment]
Resolved - didn't have bower installed...thanks for the cool app

**Comment by nmaggioni** [comment]
~~You probably missed `bower install`.~~
Awesome! Thanks for the feedback, the packaging got easier and bower is now included as a development dependency. This way you won't need to have it installed globally anymore.

Feel free to share tips & suggestions :smiley:
