### ISSUE TITLE
Install on Webserver

### ISSUE THREAD

**Issue by codingHahn** [nmaggioni/Kanbanion#6]
Would it be possible to install this application on a web server?

**Comment by nmaggioni** [comment]
Being it based on Electron, you could _theoretically_ take the guts of the application (the `app` folder) and rip out everything related to local development, but that would be quite a poor solution.

Did you take a look at [Wekan](https://wekan.github.io/), for example?

**Comment by codingHahn** [comment]
That is awesome. Thanks for the link. I'll close this now.
