### ISSUE TITLE
Allow new lists to be added

### ISSUE THREAD

**Issue by Mr-Personality** [nmaggioni/Kanbanion#9]
I would be extremely useful to be able to add custom lists, other than just the default three. I would like to set up lists for the various projects I'm working on, each with multiple cards on the list.

**Comment by nmaggioni** [comment]
Kanbanion was designed to store each project's tasks in separate files, rather than having a large amount of columns. Think of each of those files as a Trello board, not column.

**Comment by Mr-Personality** [comment]
OK thanks for the explanation. What I am really looking for is one screen where I can see all my projects at a glance - all the contents of my head on one screen - so that I don't forget anything. Currently that is my desktop, however, when things are filed away into sub-folders, it's very easy to forget them, and also impossible to see at a glance how many sub-jobs are in each folder. That's why I was looking for some kind of kanban tool to do it. This may not be the one for me, but I do like it.

**Comment by nmaggioni** [comment]
Thanks, unfortunately being so comprehensive is currently beyond the scope of this project.
A quick search turned up [kanboard](https://github.com/kanboard/kanboard), and I remember having used [Phabricator](https://www.phacility.com/phabricator/) in the past. Maybe those will better suit your use case?
